# This workflow compiles the LaTeX files in the root of this repository into
# vita.pdf and pushed it to the gh-pages branch.

name: Build CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PDFLaTeX
        shell: bash
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-latex-extra

      - name: Compile
        shell: bash
        run: make vita.pdf

      - name: Push
        shell: bash
        run: |
          git config --global user.name "James W. Johnson"
          git config --global user.email "43220904+giganano@users.noreply.github.com"
          git branch gh-pages
          git checkout gh-pages
          git pull
          git add -f vita.pdf
          git commit -m "[auto] ci: vita recompiled from main branch"
          git push -u origin gh-pages
