# This workflow compiles the LaTeX files in the root of this repository into
# vita.pdf and pushed it to the gh-pages branch.

name: Build CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest

    steps:
      - name: Install PDFLaTeX
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-latex-extra

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./main

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./gh-pages

      - name: Compile
        shell: bash
        run: |
          cd ./main
          make vita.pdf
          mv vita.pdf ../gh-pages
          make clean
          cd ../

      - name: Push
        shell: bash
        run: |
          cd ./gh-pages
          git config --global user.name "James W. Johnson"
          git config --global user.email "43220904+giganano@users.noreply.github.com"
          git add vita.pdf
          git commit -m "[auto] ci: vita recompiled from main branch"
          git push -u origin gh-pages
