# This workflow compiles the LaTeX files in the root of this repository into
# vita.pdf and pushed it to the gh-pages branch.

name: Build CV

on: [push, pull_request]

jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PdfLaTeX
        shell: bash
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-latex-extra

      - name: Compile
        shell: bash
        run: make vita.pdf

      # - name: Create Flags TeX File
      #   shell: bash
      #   run: |
      #     echo "" > flags.tex
      #     echo "\newboolean{includepubs}" >> flags.tex
      #     echo "\setboolean{includepubs}{true}" >> flags.tex
      #     echo "\begin{document}" >> flags.tex
      #     echo "\end{document}" >> flags.tex
      #     echo "" >> flags.tex
      #     cat flags.tex

      # - name: Compile
      #   uses: xu-cheng/latex-action@v2
      #   with:
      #     root_file: vita.tex

      - name: Push
        shell: bash
        run: |
          git config --global user.name "James W. Johnson"
          git config --global user.email "43220904+giganano@users.noreply.github.com"
          git branch gh-pages
          git checkout gh-pages
          git add vita.pdf
          git commit -m "[auto] ci: vita recompiled from main branch"
          git push -u origin gh-pages
